### ISSUE TITLE
How to ignore MetalLB trying to provision CPEM LoadBalancer?

### ISSUE THREAD

**Issue by Lirt** [kubernetes-sigs/cloud-provider-equinix-metal#389]
Hello,

This is rather complicated issue but I'll try to explain it in simplest way.

I have standard CPEM LoadBalancer provisioned by CPEM:
```sh
k get svc
cloud-provider-equinix-metal-kubernetes-external       LoadBalancer
```

I use MetalLB to provision additional LoadBalancer services - currently just one `ingress-nginx-caas-controller` for test case.

I have issue that MetalLB is watching service `cloud-provider-equinix-metal-kubernetes-external` by default and it fights for updates on this service with CPEM. We see this very easily, because as soon as I start MetalLB controller the `cloud-provider-equinix-metal-kubernetes-external` service changes to this (see `<pending>`):
```sh
$ k get svc
NAME                                                   TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                  AGE
cloud-provider-equinix-metal-kubernetes-external       LoadBalancer   172.26.85.165    <pending>     443:32557/TCP            49d
```

This is service description including last events to see that metallb is actually doing changes to this svc:
```yaml
Name:                     cloud-provider-equinix-metal-kubernetes-external
Namespace:                kube-system
Labels:                   <none>
Annotations:              metallb.universe.tf/address-pool: disabled-metallb-do-not-use-any-address-pool
Selector:                 <none>
Type:                     LoadBalancer
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       172.26.85.165
IPs:                      172.26.85.165
IP:                       <REDACTED>
Port:                     https  443/TCP
TargetPort:               6443/TCP
NodePort:                 https  32557/TCP
Endpoints:                10.68.53.131:6443,10.68.53.137:6443,10.68.53.139:6443
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type     Reason                Age                From                Message
  ----     ------                ----               ----                -------
  Normal   EnsuringLoadBalancer  44m                service-controller  Ensuring load balancer
  Normal   EnsuredLoadBalancer   44m                service-controller  Ensured load balancer
  Normal   EnsuringLoadBalancer  35m                service-controller  Ensuring load balancer
  Normal   EnsuredLoadBalancer   35m                service-controller  Ensured load balancer
  Normal   EnsuringLoadBalancer  17m                service-controller  Ensuring load balancer
  Normal   EnsuredLoadBalancer   17m                service-controller  Ensured load balancer
  Warning  AllocationFailed      84s (x3 over 84s)  metallb-controller  Failed to allocate IP for "kube-system/cloud-provider-equinix-metal-kubernetes-external": ["<REDACTED>"] is not allowed in config

```

EQX support told us we do 15k IP assignments per day. It's most likely caused by situation describe above.

So I wanted to use new feature of MetalLB (0.13) to set loadBalancerClass that MetalLB will be watching - https://github.com/metallb/metallb/blob/77923bc823294f2f31e68193901efa3b30faea59/controller/main.go. Simply define `--lb-class my-lb-class`.

MetalLB stops updating `cloud-provider-equinix-metal-kubernetes-external` as expected. This is good.

But then what happens is that CPEM doesn't see events on service with `loadBalancerClass`. Meaning when I create or delete service that contains `loadBalancerClass`, nothing happens in CPEM.

After long troubleshooting I found out that this behavior is defined in ServiceController that CPEM uses and is expected to happen - please see [this code](https://github.com/kubernetes/cloud-provider/blob/f270febf24b126d9400057cdf06b18d551e4f183/controllers/service/controller.go#L793-L796).

Now :smile: seeing that those 2 controllers don't work well together my question is do you have recommended way how to make this setup to work correctly without DoS-ing your API or point me to where I do a mistake if I do any.

I understand that this part of the code is very unlikely to be changed. If MetalLB decided to just use annotation to ignore service it would be all good :smiley:  but they actually used attribute that is ignored by [cloudprovider](https://github.com/kubernetes/cloud-provider/) library.

Issues is easy to replicate - here is example of service I create (this service will be unnoticed by CPEM):
```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-caas-controller
  namespace: kube-system
spec:
  type: LoadBalancer
  allocateLoadBalancerNodePorts: true
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  loadBalancerClass: my-lb-class
  ports:
  - appProtocol: http
    name: http
    port: 80
    protocol: TCP
    targetPort: http
  - appProtocol: https
    name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
```

Note: Tested with latest main (https://github.com/equinix/cloud-provider-equinix-metal/pull/386). I think this issue was present also before and is not related to recent changes.
