### ISSUE TITLE
Add option to use a specific range of IPs

### ISSUE THREAD

**Issue by enkelprifti98** [kubernetes-sigs/cloud-provider-equinix-metal#44]
This is a necessary use case for customers that bring their own IPs, or Packet global anycast IPs.

**Comment by displague** [comment]
We’ve been using kube-vip in the latest integrations (anthos in this case), metallb is not used at all.

We don’t have an annotation that the CCM can recognize to associate addresses to label in this way, that I know of.

The CCM will provision an extra IP if needed, but there is no way to request that the created IP be tagged with a tag or request an IP from reservations with a given tag.  I think a CCM recognized annotation that sets up this tag dependent behavior would allow us to ensure that multiple services claim the same address without knowing the address in advance (which is what spec.loadBalancerIP allows for today).

**Comment by deitch** [comment]
We may actually be part of the way there. The following is paraphrased from the README, in both the kube-vip and metallb sections.

For each service of `type=LoadBalancer` currently in the cluster or added:

* if an Elastic IP address reservation with the appropriate tags exists, and the Service already has that IP address affiliated with it, it is ready; ignore
* if an Elastic IP address reservation with the appropriate tags exists, and the Service does not have that IP affiliated with it, add it to the service spec (if configured for metallb, also ensure it is in the pools of the metallb ConfigMap with `auto-assign: false`)
* if an Elastic IP address reservation with the appropriate tags does not exist, create it and add it to the services spec (if configured for metallb, also ensure is in the pools of the metallb ConfigMap with `auto-assign: false`)

The question is, are those tags usable as is? Or do we need something else?

**Comment by displague** [comment]
Thanks for pointing this out, @deitch. This comment will include a little thinking-out-loud as I go through the README.

> When starting the CCM, set the env var `METAL_EIP_TAG=<tag>`, where <tag> is whatever tag you set on the EIP

This tag becomes a CCM-scoped filter, I think we would benefit from an application-scoped setting, specified within each service (as an annotation or label). 

Let's say `METAL_EIP_TAG` was set. If two Service/LoadBalancer resources were created with the same tag annotation, and we need a new /32 Elastic IP reservation to fulfill the LoadBalancer request, I would imagine the CCM would request a new reservation, tagging that reservation with both the METAL_EIP_TAG and the tag identified in the annotation.  The second LoadBalancer resource would, barring race conditions, find that same address.

If we have an existing reservation that matches both tags, but is larger than /32, we would need a way to assign the same /32 from that reservation to both services.  Perhaps the application-scoped tag on the reservation looks like: `{single-ccm-annotation-tag}:{/32 IP}`

Perhaps we already have this?

https://github.com/equinix/cloud-provider-equinix-metal#elastic-ip-configuration

* `usage="cloud-provider-equinix-metal-auto"` Is this the default `METAL_EIP_TAG`? 
* `service="<service-hash>"` This seems close to the `tag` filter idea
* `cluster=<clusterID>` This seems related to https://github.com/equinix/cloud-provider-equinix-metal/issues/154

The suggestion I am mulling around is whether we should introduce a tag such as:
* `annotation="keyword{",/32 IP" pulled from the reservation if the reservation is larger than /32}"`

Multiple of these could be added to an existing reservation or added to a new reservation that uses the annotation.

```
kind: Service
metadata:
  annotations:
    metal.equinix.com/ip-reservation-tag-annotation: keyword
    metal.equinix.com/ip-reservation-cidr: 28
spec:
  type: LoadBalancer
```

If the CIDR is specified, we would create an IP reservation request of that size.  If not specified, we would find any reservation with the keyword in the annotation tag, or create a /32 with that annotation tag.

**Comment by displague** [comment]
To draw a /32 from an existing reservation, 

```
kind: Service
metadata:
  annotations:
    metal.equinix.com/ip-reservation-id: {uuid}
    metal.equinix.com/ip-reservation-cidr: 28 # optional, used for creates
spec:
  type: LoadBalancer
```

or


```
kind: Service
metadata:
  annotations:
    metal.equinix.com/ip-reservation-tag: {keyword}
    metal.equinix.com/ip-reservation-cidr: 28 # optional, used for creates
spec:
  type: LoadBalancer
```
